### ISSUE TITLE
Only e-paper worked

### ISSUE THREAD

**Issue by rgodragon** [gigoh/it8951-pi-desktop#1]
Thank you for sharing your code.

I tried it, however only the e-paper worked and my monitor(connected by HDMI) didn't show anything.

Here is the file that you requested.
[config.txt](https://github.com/gigoh/it8951-pi-desktop/files/4710478/config.txt)

**Comment by gigoh** [comment]
rgodragon, thanks for the report.

I couldn't figure out the problem from the file.
It seems that some configuration is different from my test environment.

Could you check the file exists or not in the path below?
`/usr/share/X11/xorg.conf.d/99-fbturbo.conf`

If the file is missing or empty, uncomment device sections in `990-dualmonitor.conf` and retry.
I found that `99-fbturbo.conf` is removed if once KMS driver is activated.

**Comment by gigoh** [comment]
Does it works for you?

If it works, you can ask me to close the issue or you can do it by yourself :)
